trigger: none
pr: none

pool:
  vmImage: 'ubuntu-latest'

jobs:
- job: HelloWorld
  steps:
  - task: PowerShell@2
    inputs:
      targetType: 'inline'
      script: |
        Write-Output "Hello World!"